// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AttendanceManagementPayrollSystem.Models;

public partial class AttendanceManagementPayrollSystemContext : DbContext
{
    public AttendanceManagementPayrollSystemContext(DbContextOptions<AttendanceManagementPayrollSystemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AllowanceType> AllowanceTypes { get; set; }

    public virtual DbSet<Clockin> Clockins { get; set; }

    public virtual DbSet<ClockinComponent> ClockinComponents { get; set; }

    public virtual DbSet<DailyShift> DailyShifts { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<DepartmentHolidayCalender> DepartmentHolidayCalenders { get; set; }

    public virtual DbSet<DepartmentWeeklyShift> DepartmentWeeklyShifts { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<EmployeeAllowance> EmployeeAllowances { get; set; }

    public virtual DbSet<EmployeeBalance> EmployeeBalances { get; set; }

    public virtual DbSet<EmployeeDependent> EmployeeDependents { get; set; }

    public virtual DbSet<EmployeePermission> EmployeePermissions { get; set; }

    public virtual DbSet<EmployeeRole> EmployeeRoles { get; set; }

    public virtual DbSet<HolidayCalendar> HolidayCalendars { get; set; }

    public virtual DbSet<InsuranceRate> InsuranceRates { get; set; }

    public virtual DbSet<Kpi> Kpis { get; set; }

    public virtual DbSet<Kpicomponent> Kpicomponents { get; set; }

    public virtual DbSet<LeaveRequest> LeaveRequests { get; set; }

    public virtual DbSet<LeaveType> LeaveTypes { get; set; }

    public virtual DbSet<OvertimeRate> OvertimeRates { get; set; }

    public virtual DbSet<OvertimeRequest> OvertimeRequests { get; set; }

    public virtual DbSet<PayRun> PayRuns { get; set; }

    public virtual DbSet<PayRunComponent> PayRunComponents { get; set; }

    public virtual DbSet<PayRunItem> PayRunItems { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<SalaryPolicy> SalaryPolicies { get; set; }

    public virtual DbSet<Tax> Taxes { get; set; }

    public virtual DbSet<TaxBracket> TaxBrackets { get; set; }

    public virtual DbSet<WeeklyShift> WeeklyShifts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AllowanceType>(entity =>
        {
            entity.HasKey(e => e.TypeId).HasName("PK__Allowanc__2C00059854A2BE75");

            entity.ToTable("AllowanceType");

            entity.Property(e => e.TypeId).HasColumnName("type_id");
            entity.Property(e => e.CalculationType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("calculation_type");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.EffectiveStartDate).HasColumnName("effective_start_date");
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("type_name");
            entity.Property(e => e.Value)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("value");
        });

        modelBuilder.Entity<Clockin>(entity =>
        {
            entity.HasKey(e => e.CloId);

            entity.ToTable("Clockin");

            entity.HasIndex(e => e.CloId, "constraint_name").IsUnique();

            entity.Property(e => e.CloId).HasColumnName("clo_id");
            entity.Property(e => e.ClockLog).HasMaxLength(1000);
            entity.Property(e => e.Date)
                .HasColumnType("datetime")
                .HasColumnName("date");
            entity.Property(e => e.EmpId).HasColumnName("emp_id");
            entity.Property(e => e.ScheduledHours).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.ScheduledUnits).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.WorkHourBreakdown).HasMaxLength(1000);
            entity.Property(e => e.WorkHours).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.WorkUnitBreakdown).HasMaxLength(1000);
            entity.Property(e => e.WorkUnits).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Emp).WithMany(p => p.Clockins)
                .HasForeignKey(d => d.EmpId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Clockin_Employee");
        });

        modelBuilder.Entity<ClockinComponent>(entity =>
        {
            entity.ToTable("ClockinComponent");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CheckIn)
                .HasColumnType("datetime")
                .HasColumnName("check_in");
            entity.Property(e => e.CheckOut)
                .HasColumnType("datetime")
                .HasColumnName("check_out");
            entity.Property(e => e.CloId).HasColumnName("clo_id");
            entity.Property(e => e.ClockinLog)
                .HasMaxLength(50)
                .HasColumnName("clockin_log");
            entity.Property(e => e.Date)
                .HasColumnType("datetime")
                .HasColumnName("date");
            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .HasColumnName("description");
            entity.Property(e => e.ScheduledHours)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("scheduled_hours");
            entity.Property(e => e.ScheduledUnits)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("scheduled_units");
            entity.Property(e => e.Shift)
                .HasMaxLength(50)
                .HasColumnName("shift");
            entity.Property(e => e.WorkHours)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("work_hours");
            entity.Property(e => e.WorkUnits)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("work_units");

            entity.HasOne(d => d.Clo).WithMany(p => p.ClockinComponents)
                .HasForeignKey(d => d.CloId)
                .HasConstraintName("FK_ClockinComponent_ClockinComponent");
        });

        modelBuilder.Entity<DailyShift>(entity =>
        {
            entity.HasKey(e => e.ShiftId).HasName("PK__DailyShi__1BC1E2CF1365459F");

            entity.ToTable("DailyShift");

            entity.Property(e => e.ShiftDescription).HasMaxLength(100);
            entity.Property(e => e.ShiftHours).HasMaxLength(100);
            entity.Property(e => e.ShiftName).HasMaxLength(100);
            entity.Property(e => e.ShiftString).HasMaxLength(200);
            entity.Property(e => e.ShiftWorkUnit).HasColumnType("decimal(4, 2)");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.DepId);

            entity.ToTable("Department");

            entity.Property(e => e.DepId).HasColumnName("dep_id");
            entity.Property(e => e.DepName)
                .HasMaxLength(50)
                .HasColumnName("dep_name");
            entity.Property(e => e.DepType)
                .HasMaxLength(50)
                .HasColumnName("dep_type");
            entity.Property(e => e.DepUnactive)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Department_dep_unactive")
                .HasColumnName("dep_unactive");
        });

        modelBuilder.Entity<DepartmentHolidayCalender>(entity =>
        {
            entity.HasKey(e => e.DepHolidayCalendarId);

            entity.ToTable("DepartmentHolidayCalender");

            entity.Property(e => e.DepHolidayCalendarId).HasColumnName("dep_holiday_calendar_id");
            entity.Property(e => e.DepId).HasColumnName("dep_id");
            entity.Property(e => e.EndDate)
                .HasColumnType("datetime")
                .HasColumnName("end_date");
            entity.Property(e => e.HolidayId).HasColumnName("holiday_id");
            entity.Property(e => e.StartDate)
                .HasColumnType("datetime")
                .HasColumnName("start_date");

            entity.HasOne(d => d.Dep).WithMany(p => p.DepartmentHolidayCalenders)
                .HasForeignKey(d => d.DepId)
                .HasConstraintName("FK_DepartmentHolidayCalender_Department");

            entity.HasOne(d => d.Holiday).WithMany(p => p.DepartmentHolidayCalenders)
                .HasForeignKey(d => d.HolidayId)
                .HasConstraintName("FK_DepartmentHolidayCalender_HolidayCalendar");
        });

        modelBuilder.Entity<DepartmentWeeklyShift>(entity =>
        {
            entity.HasKey(e => e.DeptShiftId).HasName("PK__Departme__E496BB67FB72F329");

            entity.ToTable("DepartmentWeeklyShift");

            entity.Property(e => e.DeptShiftId).HasColumnName("dept_shift_id");
            entity.Property(e => e.DepId).HasColumnName("dep_id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.ShiftId).HasColumnName("shift_id");

            entity.HasOne(d => d.Dep).WithMany(p => p.DepartmentWeeklyShifts)
                .HasForeignKey(d => d.DepId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DepartmentShift_Department");

            entity.HasOne(d => d.Shift).WithMany(p => p.DepartmentWeeklyShifts)
                .HasForeignKey(d => d.ShiftId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DepartmentShift_WeeklyShift");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmpId);

            entity.ToTable("Employee");

            entity.Property(e => e.EmpId).HasColumnName("emp_id");
            entity.Property(e => e.ClockinId).HasColumnName("clockin_id");
            entity.Property(e => e.DepId).HasColumnName("dep_id");
            entity.Property(e => e.EmpDob).HasColumnName("emp_dob");
            entity.Property(e => e.EmpName)
                .HasMaxLength(50)
                .HasColumnName("emp_name");
            entity.Property(e => e.EmpPhoneNumber)
                .HasMaxLength(13)
                .IsUnicode(false)
                .HasColumnName("emp_phone_number");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("password_hash");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("username");

            entity.HasOne(d => d.Dep).WithMany(p => p.Employees)
                .HasForeignKey(d => d.DepId)
                .HasConstraintName("FK_Employee_Department");
        });

        modelBuilder.Entity<EmployeeAllowance>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3213E83F3CBF75FB");

            entity.ToTable("EmployeeAllowance");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CustomValue)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("custom_value");
            entity.Property(e => e.EmpId).HasColumnName("emp_id");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("Active")
                .HasColumnName("status");
            entity.Property(e => e.TypeId).HasColumnName("type_id");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.EmployeeAllowanceCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EmployeeAllowance_CreatedBy");

            entity.HasOne(d => d.Emp).WithMany(p => p.EmployeeAllowanceEmps)
                .HasForeignKey(d => d.EmpId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EmployeeAllowance_Employee");

            entity.HasOne(d => d.Type).WithMany(p => p.EmployeeAllowances)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EmployeeAllowance_AllowanceType");
        });

        modelBuilder.Entity<EmployeeBalance>(entity =>
        {
            entity.ToTable("EmployeeBalance");

            entity.Property(e => e.EmpId).HasColumnName("emp_id");
            entity.Property(e => e.LastUpdated)
                .HasColumnType("datetime")
                .HasColumnName("last_updated");
            entity.Property(e => e.Overtime)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("0.00|0.00|0.00")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_EmployeeBalance_overtime")
                .HasColumnName("overtime");
            entity.Property(e => e.Pto)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("0.00|0.00|0.00")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Table_1_leave")
                .HasColumnName("pto");
            entity.Property(e => e.Sick)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("0.00|0.00|0.00")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_EmployeeBalance_sick")
                .HasColumnName("sick");
            entity.Property(e => e.Vacation)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("0.00|0.00|0.00")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_EmployeeBalance_vacation")
                .HasColumnName("vacation");

            entity.HasOne(d => d.Emp).WithMany(p => p.EmployeeBalances)
                .HasForeignKey(d => d.EmpId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EmployeeBalance_Employee");
        });

        modelBuilder.Entity<EmployeeDependent>(entity =>
        {
            entity.HasKey(e => e.DependentId).HasName("PK__Employee__9BC67C11944A6DEC");

            entity.ToTable("EmployeeDependent");

            entity.Property(e => e.DependentId).HasColumnName("DependentID");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.EffectiveStartDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.EmployeeId).HasColumnName("EmployeeID");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Gender)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.NationalId)
                .HasMaxLength(50)
                .HasColumnName("NationalID");
            entity.Property(e => e.Proof).HasMaxLength(50);
            entity.Property(e => e.Relationship)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Employee).WithMany(p => p.EmployeeDependents)
                .HasForeignKey(d => d.EmployeeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EmployeeDependent_Employee");
        });

        modelBuilder.Entity<EmployeePermission>(entity =>
        {
            entity.HasKey(e => e.UserPermissionId).HasName("PK__Employee__A90F88D24E4C1F13");

            entity.ToTable("EmployeePermission");

            entity.Property(e => e.UserPermissionId).HasColumnName("UserPermissionID");
            entity.Property(e => e.PermissionId).HasColumnName("PermissionID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Permission).WithMany(p => p.EmployeePermissions)
                .HasForeignKey(d => d.PermissionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__EmployeeP__Permi__31B762FC");

            entity.HasOne(d => d.User).WithMany(p => p.EmployeePermissions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserPermi__UserI__72910220");
        });

        modelBuilder.Entity<EmployeeRole>(entity =>
        {
            entity.HasKey(e => new { e.EmpId, e.RoleId }).HasName("PK__UserRole__760965CC5651F5D8");

            entity.ToTable("EmployeeRole");

            entity.Property(e => e.EmpId).HasColumnName("emp_id");
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.StartDate).HasColumnType("datetime");

            entity.HasOne(d => d.Emp).WithMany(p => p.EmployeeRoles)
                .HasForeignKey(d => d.EmpId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserRoles__emp_i__681373AD");

            entity.HasOne(d => d.Role).WithMany(p => p.EmployeeRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__EmployeeR__RoleI__339FAB6E");
        });

        modelBuilder.Entity<HolidayCalendar>(entity =>
        {
            entity.HasKey(e => e.HolidayId).HasName("PK__HolidayC__253884EAB1792683");

            entity.ToTable("HolidayCalendar");

            entity.Property(e => e.HolidayId).HasColumnName("holiday_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.HolidayName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("holiday_name");
            entity.Property(e => e.PeriodYear)
                .HasColumnType("datetime")
                .HasColumnName("period_year");
        });

        modelBuilder.Entity<InsuranceRate>(entity =>
        {
            entity.HasKey(e => e.RateSetId).HasName("PK__Insuranc__99F858C962036414");

            entity.ToTable("InsuranceRate");

            entity.Property(e => e.CapRule).HasMaxLength(255);
            entity.Property(e => e.EmployeeRate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.EmployerRate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.LawCode).HasMaxLength(255);
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Kpi>(entity =>
        {
            entity.ToTable("KPI");

            entity.Property(e => e.KpiId).HasColumnName("kpi_id");
            entity.Property(e => e.AssignedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_KPI_assigned_at")
                .HasColumnType("datetime")
                .HasColumnName("assigned_at");
            entity.Property(e => e.AssignedBy).HasColumnName("assigned_by");
            entity.Property(e => e.EmpId).HasColumnName("emp_id");
            entity.Property(e => e.KpiRate).HasColumnName("kpi_rate");
            entity.Property(e => e.PeriodMonth).HasColumnName("period_month");
            entity.Property(e => e.PeriodYear).HasColumnName("period_year");
            entity.Property(e => e.Prorate)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_KPI_prorate")
                .HasColumnName("prorate");

            entity.HasOne(d => d.AssignedByNavigation).WithMany(p => p.KpiAssignedByNavigations)
                .HasForeignKey(d => d.AssignedBy)
                .HasConstraintName("FK_KPI_Employee1");

            entity.HasOne(d => d.Emp).WithMany(p => p.KpiEmps)
                .HasForeignKey(d => d.EmpId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KPI_Employee");
        });

        modelBuilder.Entity<Kpicomponent>(entity =>
        {
            entity.HasKey(e => e.KpiCompId).HasName("PK_Table_1");

            entity.ToTable("KPIComponent");

            entity.Property(e => e.KpiCompId).HasColumnName("kpi_comp_id");
            entity.Property(e => e.AchievedValue).HasColumnName("achieved_value");
            entity.Property(e => e.AssignedScore)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("assigned_score");
            entity.Property(e => e.AssignerComment)
                .HasMaxLength(100)
                .HasColumnName("assigner_comment");
            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .HasColumnName("description");
            entity.Property(e => e.KpiId).HasColumnName("kpi_id");
            entity.Property(e => e.Name)
                .HasMaxLength(30)
                .HasColumnName("name");
            entity.Property(e => e.SelfComment)
                .HasMaxLength(100)
                .HasColumnName("self_comment");
            entity.Property(e => e.SelfScore)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("self_score");
            entity.Property(e => e.TargetValue).HasColumnName("target_value");
            entity.Property(e => e.Weight).HasColumnName("weight");

            entity.HasOne(d => d.Kpi).WithMany(p => p.Kpicomponents)
                .HasForeignKey(d => d.KpiId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Table_1_KPI");
        });

        modelBuilder.Entity<LeaveRequest>(entity =>
        {
            entity.HasKey(e => e.ReqId).HasName("PK__LeaveReq__1513A6FBD8724243");

            entity.ToTable("LeaveRequest");

            entity.Property(e => e.ReqId).HasColumnName("req_id");
            entity.Property(e => e.ApprovedBy).HasColumnName("approved_by");
            entity.Property(e => e.ApprovedDate).HasColumnName("approved_date");
            entity.Property(e => e.EmpId).HasColumnName("emp_id");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.NumbersOfDays)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("numbers_of_days");
            entity.Property(e => e.Reason)
                .HasMaxLength(255)
                .HasColumnName("reason");
            entity.Property(e => e.ReqDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("req_date");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("status");
            entity.Property(e => e.TypeId).HasColumnName("type_id");

            entity.HasOne(d => d.ApprovedByNavigation).WithMany(p => p.LeaveRequestApprovedByNavigations)
                .HasForeignKey(d => d.ApprovedBy)
                .HasConstraintName("FK__LeaveRequ__appro__3E1D39E1");

            entity.HasOne(d => d.Emp).WithMany(p => p.LeaveRequestEmps)
                .HasForeignKey(d => d.EmpId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LeaveRequ__emp_i__3A4CA8FD");

            entity.HasOne(d => d.Type).WithMany(p => p.LeaveRequests)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LeaveRequ__type___3A4CA8FD");
        });

        modelBuilder.Entity<LeaveType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LeaveTyp__3213E83F97ABA29F");

            entity.ToTable("LeaveType");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.PaidPercent)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("paid_percent");
            entity.Property(e => e.RequiresApproval)
                .HasDefaultValue(true)
                .HasColumnName("requires_approval");
        });

        modelBuilder.Entity<OvertimeRate>(entity =>
        {
            entity.ToTable("OvertimeRate");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.EffectiveDate)
                .HasColumnType("datetime")
                .HasColumnName("effective_date");
            entity.Property(e => e.OvertimeType)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("overtime_type");
            entity.Property(e => e.RateMultiplier)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("rate_multiplier");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.OvertimeRates)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_OvertimeRate_Employee");
        });

        modelBuilder.Entity<OvertimeRequest>(entity =>
        {
            entity.HasKey(e => e.ReqId).HasName("PK__Overtime__1513A6FB9386589F");

            entity.ToTable("OvertimeRequest");

            entity.Property(e => e.ReqId).HasColumnName("req_id");
            entity.Property(e => e.ApprovedBy).HasColumnName("approved_by");
            entity.Property(e => e.ApprovedDate).HasColumnName("approved_date");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("created_date");
            entity.Property(e => e.EmpId).HasColumnName("emp_id");
            entity.Property(e => e.EndTime).HasColumnName("end_time");
            entity.Property(e => e.Hours)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("hours");
            entity.Property(e => e.LinkedPayrollRunId).HasColumnName("linked_payroll_run_id");
            entity.Property(e => e.OvertimeType).HasColumnName("overtime_type");
            entity.Property(e => e.Reason)
                .HasMaxLength(255)
                .HasColumnName("reason");
            entity.Property(e => e.ReqDate).HasColumnName("req_date");
            entity.Property(e => e.StartTime).HasColumnName("start_time");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Pending")
                .HasColumnName("status");

            entity.HasOne(d => d.ApprovedByNavigation).WithMany(p => p.OvertimeRequestApprovedByNavigations)
                .HasForeignKey(d => d.ApprovedBy)
                .HasConstraintName("FK_OvertimeRequest_ApprovedBy");

            entity.HasOne(d => d.Emp).WithMany(p => p.OvertimeRequestEmps)
                .HasForeignKey(d => d.EmpId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OvertimeRequest_Employee");

            entity.HasOne(d => d.LinkedPayrollRun).WithMany(p => p.OvertimeRequests)
                .HasForeignKey(d => d.LinkedPayrollRunId)
                .HasConstraintName("FK_OvertimeRequest_PayrollRun");

            entity.HasOne(d => d.OvertimeTypeNavigation).WithMany(p => p.OvertimeRequests)
                .HasForeignKey(d => d.OvertimeType)
                .HasConstraintName("FK_OvertimeRequest_OvertimeRate");
        });

        modelBuilder.Entity<PayRun>(entity =>
        {
            entity.HasKey(e => e.PayrollRunId).HasName("PK__PayrollR__042B3F66A4356420");

            entity.ToTable("PayRun");

            entity.Property(e => e.PayrollRunId).HasColumnName("payroll_run_id");
            entity.Property(e => e.ApprovedFinalAt)
                .HasColumnType("datetime")
                .HasColumnName("approved_final_at");
            entity.Property(e => e.ApprovedFinalBy).HasColumnName("approved_final_by");
            entity.Property(e => e.ApprovedFirstAt)
                .HasColumnType("datetime")
                .HasColumnName("approved_first_at");
            entity.Property(e => e.ApprovedFirstBy).HasColumnName("approved_first_by");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__PayrollRu__creat__7C4F7684")
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.PeriodMonth).HasColumnName("period_month");
            entity.Property(e => e.PeriodYear).HasColumnName("period_year");
            entity.Property(e => e.RejectedAt)
                .HasColumnType("datetime")
                .HasColumnName("rejected_at");
            entity.Property(e => e.RejectedBy).HasColumnName("rejected_by");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Pending")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PayrollRun_status")
                .HasColumnName("status");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("regular")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PayRun_type")
                .HasColumnName("type");

            entity.HasOne(d => d.ApprovedFinalByNavigation).WithMany(p => p.PayRunApprovedFinalByNavigations)
                .HasForeignKey(d => d.ApprovedFinalBy)
                .HasConstraintName("FK_PayrollRun_Employee");

            entity.HasOne(d => d.ApprovedFirstByNavigation).WithMany(p => p.PayRunApprovedFirstByNavigations)
                .HasForeignKey(d => d.ApprovedFirstBy)
                .HasConstraintName("FK__PayrollRu__appro__44CA3770");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.PayRunCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK__PayrollRu__creat__42E1EEFE");

            entity.HasOne(d => d.RejectedByNavigation).WithMany(p => p.PayRunRejectedByNavigations)
                .HasForeignKey(d => d.RejectedBy)
                .HasConstraintName("FK_PayRun_Employee");
        });

        modelBuilder.Entity<PayRunComponent>(entity =>
        {
            entity.ToTable("PayRunComponent");

            entity.Property(e => e.PayRunComponentId).HasColumnName("pay_run_component_id");
            entity.Property(e => e.Amount)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PayRunComponent_amount")
                .HasColumnType("decimal(12, 2)")
                .HasColumnName("amount");
            entity.Property(e => e.ComponentCode)
                .HasMaxLength(20)
                .HasDefaultValue("OTHERS")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PayRunComponent_component_code")
                .HasColumnName("component_code");
            entity.Property(e => e.ComponentType)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("component_type");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PayRunComponent_created_at")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .HasColumnName("description");
            entity.Property(e => e.Insurable)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PayRunComponent_insurable")
                .HasColumnName("insurable");
            entity.Property(e => e.PayRunItemId).HasColumnName("pay_run_item_id");
            entity.Property(e => e.Taxable)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PayRunComponent_taxable")
                .HasColumnName("taxable");

            entity.HasOne(d => d.PayRunItem).WithMany(p => p.PayRunComponents)
                .HasForeignKey(d => d.PayRunItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PayRunComponent_PayRunItem");
        });

        modelBuilder.Entity<PayRunItem>(entity =>
        {
            entity.HasKey(e => e.PayRunItemId).HasName("PK_PayRunItems");

            entity.ToTable("PayRunItem");

            entity.Property(e => e.PayRunItemId).HasColumnName("pay_run_item_id");
            entity.Property(e => e.Deductions)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PayRunItems_deductions")
                .HasColumnType("decimal(12, 2)")
                .HasColumnName("deductions");
            entity.Property(e => e.EmpId).HasColumnName("emp_id");
            entity.Property(e => e.GrossPay)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PayRunItems_gross_pay")
                .HasColumnType("decimal(12, 2)")
                .HasColumnName("gross_pay");
            entity.Property(e => e.NetPay)
                .HasColumnType("decimal(12, 2)")
                .HasColumnName("net_pay");
            entity.Property(e => e.Notes)
                .HasMaxLength(100)
                .HasColumnName("notes");
            entity.Property(e => e.PayRunId).HasColumnName("pay_run_id");

            entity.HasOne(d => d.Emp).WithMany(p => p.PayRunItems)
                .HasForeignKey(d => d.EmpId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PayRunItem_Employee");

            entity.HasOne(d => d.PayRun).WithMany(p => p.PayRunItems)
                .HasForeignKey(d => d.PayRunId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PayRunItem_PayRun");
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasKey(e => e.PermissionId).HasName("PK__Permissi__EFA6FB0F8614E353");

            entity.HasIndex(e => e.PermissionName, "UQ__Permissi__0FFDA357904C4BA4").IsUnique();

            entity.Property(e => e.PermissionId).HasColumnName("PermissionID");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.PermissionName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE3A52E32439");

            entity.HasIndex(e => e.RoleName, "UQ__Roles__8A2B6160E134A1B9").IsUnique();

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SecurityLevel)
                .HasDefaultValue((byte)1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Roles_SecurityLevel");

            entity.HasMany(d => d.Permissions).WithMany(p => p.Roles)
                .UsingEntity<Dictionary<string, object>>(
                    "RolePermission",
                    r => r.HasOne<Permission>().WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__RolePermi__Permi__46B27FE2"),
                    l => l.HasOne<Role>().WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__RolePermi__RoleI__47A6A41B"),
                    j =>
                    {
                        j.HasKey("RoleId", "PermissionId").HasName("PK__RolePerm__120F469AC923DC9A");
                        j.ToTable("RolePermission");
                        j.IndexerProperty<int>("RoleId").HasColumnName("RoleID");
                        j.IndexerProperty<int>("PermissionId").HasColumnName("PermissionID");
                    });
        });

        modelBuilder.Entity<SalaryPolicy>(entity =>
        {
            entity.HasKey(e => e.SalId);

            entity.ToTable("SalaryPolicy");

            entity.Property(e => e.SalId).HasColumnName("sal_id");
            entity.Property(e => e.EffectiveFrom).HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasAnnotation("Relational:DefaultConstraintName", "DF_SalaryPolicy_IsActive");
            entity.Property(e => e.OverclockMultiplier)
                .HasDefaultValue(1.50m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SalaryPolicy_OverclockMultiplier")
                .HasColumnType("decimal(5, 2)");
            entity.Property(e => e.SalaryPolicyName)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.WorkUnitValue).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.YearlyPto)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SalaryPolicy_YearlyPTO")
                .HasColumnName("YearlyPTO");
        });

        modelBuilder.Entity<Tax>(entity =>
        {
            entity.ToTable("Tax");

            entity.Property(e => e.TaxId).HasColumnName("TaxID");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Tax_IsActive");
            entity.Property(e => e.TaxName).HasMaxLength(50);
        });

        modelBuilder.Entity<TaxBracket>(entity =>
        {
            entity.HasKey(e => e.BracketId).HasName("PK__TaxBrack__8AC2D7999988846D");

            entity.ToTable("TaxBracket");

            entity.Property(e => e.BracketId).HasColumnName("BracketID");
            entity.Property(e => e.LowerBound).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Rate).HasColumnType("decimal(5, 4)");
            entity.Property(e => e.TaxId).HasColumnName("TaxID");
            entity.Property(e => e.UpperBound).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Tax).WithMany(p => p.TaxBrackets)
                .HasForeignKey(d => d.TaxId)
                .HasConstraintName("FK_TaxBracket_Tax");
        });

        modelBuilder.Entity<WeeklyShift>(entity =>
        {
            entity.HasKey(e => e.ShiftId).HasName("PK__WeeklySh__C0A83881FC093655");

            entity.ToTable("WeeklyShift");

            entity.Property(e => e.ShiftDescription).HasMaxLength(100);
            entity.Property(e => e.ShiftName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.FriDailyShift).WithMany(p => p.WeeklyShiftFriDailyShifts)
                .HasForeignKey(d => d.FriDailyShiftId)
                .HasConstraintName("FK_WeeklyShift_DailyShift_Fri");

            entity.HasOne(d => d.MonDailyShift).WithMany(p => p.WeeklyShiftMonDailyShifts)
                .HasForeignKey(d => d.MonDailyShiftId)
                .HasConstraintName("FK_WeeklyShift_DailyShift_Mon");

            entity.HasOne(d => d.SatDailyShift).WithMany(p => p.WeeklyShiftSatDailyShifts)
                .HasForeignKey(d => d.SatDailyShiftId)
                .HasConstraintName("FK_WeeklyShift_DailyShift_Sat");

            entity.HasOne(d => d.SunDailyShift).WithMany(p => p.WeeklyShiftSunDailyShifts)
                .HasForeignKey(d => d.SunDailyShiftId)
                .HasConstraintName("FK_WeeklyShift_DailyShift_Sun");

            entity.HasOne(d => d.ThuDailyShift).WithMany(p => p.WeeklyShiftThuDailyShifts)
                .HasForeignKey(d => d.ThuDailyShiftId)
                .HasConstraintName("FK_WeeklyShift_DailyShift_Thu");

            entity.HasOne(d => d.TueDailyShift).WithMany(p => p.WeeklyShiftTueDailyShifts)
                .HasForeignKey(d => d.TueDailyShiftId)
                .HasConstraintName("FK_WeeklyShift_DailyShift_Tue");

            entity.HasOne(d => d.WedDailyShift).WithMany(p => p.WeeklyShiftWedDailyShifts)
                .HasForeignKey(d => d.WedDailyShiftId)
                .HasConstraintName("FK_WeeklyShift_DailyShift_Wed");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}