// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class AllowanceType
{
    public int TypeId { get; set; }

    public string TypeName { get; set; }

    public string CalculationType { get; set; }

    public decimal? Value { get; set; }

    public DateOnly EffectiveStartDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<EmployeeAllowance> EmployeeAllowances { get; set; } = new List<EmployeeAllowance>();
}