// <auto-generated> Hand-authored to match existing database schema. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class Bonus
{
	public int BonusId { get; set; }
	public string BonusName { get; set; }
	public decimal BonusAmount { get; set; }
	public DateTime? CreatedAt { get; set; }
	public DateOnly? BonusPeriod { get; set; }
	public virtual ICollection<EmpBonus> EmpBonuses { get; set; } = new List<EmpBonus>();
}


