// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class Bonu
{
    public int BonusId { get; set; }

    public string BonusName { get; set; }

    public decimal BonusAmount { get; set; }

    public DateOnly BonusPeriod { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<EmpBonu> EmpBonus { get; set; } = new List<EmpBonu>();
}