// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class ClockinComponent
{
    public int Id { get; set; }

    public int? CloId { get; set; }

    public string Shift { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? CheckIn { get; set; }

    public DateTime? CheckOut { get; set; }

    public string ClockinLog { get; set; }

    public string Description { get; set; }

    public decimal? WorkHours { get; set; }

    public decimal? ScheduledHours { get; set; }

    public decimal? WorkUnits { get; set; }

    public decimal? ScheduledUnits { get; set; }

    public decimal? OverridedWorkunits { get; set; }

    public virtual Clockin Clo { get; set; }

    public virtual ICollection<ClockInAdjustmentRequest> ClockInAdjustmentRequests { get; set; } = new List<ClockInAdjustmentRequest>();
}