// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class ClockInAdjustmentRequest
{
    public int RequestId { get; set; }

    public int EmployeeId { get; set; }

    public int ClockInComponentId { get; set; }

    public decimal RequestedValue { get; set; }

    public string Message { get; set; }

    public string Attachment { get; set; }

    public string Status { get; set; }

    public int? ApproverId { get; set; }

    public string Comment { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Employee Approver { get; set; }

    public virtual ClockinComponent ClockInComponent { get; set; }

    public virtual Employee Employee { get; set; }
}