// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class Department
{
    public int DepId { get; set; }

    public string DepName { get; set; }

    public string DepType { get; set; }

    public bool DepUnactive { get; set; }

    public virtual ICollection<DepartmentHolidayCalender> DepartmentHolidayCalenders { get; set; } = new List<DepartmentHolidayCalender>();

    public virtual ICollection<DepartmentWeeklyShift> DepartmentWeeklyShifts { get; set; } = new List<DepartmentWeeklyShift>();

    public virtual ICollection<EmpBonu> EmpBonus { get; set; } = new List<EmpBonu>();

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}