// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class DepartmentWeeklyShift
{
    public int DeptShiftId { get; set; }

    public int DepId { get; set; }

    public int ShiftId { get; set; }

    public bool IsActive { get; set; }

    public virtual Department Dep { get; set; }

    public virtual WeeklyShift Shift { get; set; }
}