// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class DepartmentHolidayCalender
{
    public int? DepId { get; set; }

    public int? HolidayId { get; set; }

    public int DepHolidayCalendarId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public virtual Department Dep { get; set; }

    public virtual HolidayCalendar Holiday { get; set; }
}