// <auto-generated> Hand-authored to match existing database schema. </auto-generated>
#nullable disable
using System;

namespace AttendanceManagementPayrollSystem.Models;

public partial class EmpBonus
{
	public int EmpBonusId { get; set; }
	public int EmpId { get; set; }
	public int BonusId { get; set; }
	public int? DepId { get; set; }

	public virtual Employee Emp { get; set; }
	public virtual Bonus Bonus { get; set; }
	public virtual Department Dep { get; set; }
}


