// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class EmpBonu
{
    public int EmpBonusId { get; set; }

    public int EmpId { get; set; }

    public int BonusId { get; set; }

    public int? DepId { get; set; }

    public virtual Bonu Bonus { get; set; }

    public virtual Department Dep { get; set; }

    public virtual Employee Emp { get; set; }
}