// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class HolidayCalendar
{
    public int HolidayId { get; set; }

    public string HolidayName { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? PeriodYear { get; set; }

    public virtual ICollection<DepartmentHolidayCalender> DepartmentHolidayCalenders { get; set; } = new List<DepartmentHolidayCalender>();
}