// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class LeaveRequest
{
    public int ReqId { get; set; }

    public int EmpId { get; set; }

    public int TypeId { get; set; }

    public DateOnly ReqDate { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public decimal NumbersOfDays { get; set; }

    public string? Reason { get; set; }

    public string Status { get; set; }

    public int? ApprovedBy { get; set; }

    public DateOnly? ApprovedDate { get; set; }

    public virtual Employee ApprovedByNavigation { get; set; }

    public virtual Employee Emp { get; set; }

    public virtual LeaveType Type { get; set; }
}