// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class LeaveType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool RequiresApproval { get; set; }

    public decimal PaidPercent { get; set; }

    public virtual ICollection<LeaveRequest> LeaveRequests { get; set; } = new List<LeaveRequest>();
}