// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class OvertimeRequest
{
    public int ReqId { get; set; }

    public int EmpId { get; set; }

    public DateOnly ReqDate { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public decimal? Hours { get; set; }

    public int? OvertimeType { get; set; }

    public string Reason { get; set; }

    public string Status { get; set; }

    public DateOnly? CreatedDate { get; set; }

    public int? ApprovedBy { get; set; }

    public DateOnly? ApprovedDate { get; set; }

    public int? LinkedPayrollRunId { get; set; }

    public virtual Employee ApprovedByNavigation { get; set; }

    public virtual Employee Emp { get; set; }

    public virtual PayRun LinkedPayrollRun { get; set; }

    public virtual OvertimeRate OvertimeTypeNavigation { get; set; }
}