// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class PayRun
{
    public int PayrollRunId { get; set; }

    public string Name { get; set; }

    public int PeriodMonth { get; set; }

    public int PeriodYear { get; set; }

    public string Status { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? ApprovedFirstBy { get; set; }

    public DateTime? ApprovedFirstAt { get; set; }

    public int? ApprovedFinalBy { get; set; }

    public DateTime? ApprovedFinalAt { get; set; }

    public string Type { get; set; }

    public int? RejectedBy { get; set; }

    public DateTime? RejectedAt { get; set; }

    public int? TaxId { get; set; }

    public int? SocialInsuranceId { get; set; }

    public int? HealthInsuranceId { get; set; }

    public int? UnemployeeInsuranceId { get; set; }

    public int? SalaryPolicyId { get; set; }

    public virtual Employee ApprovedFinalByNavigation { get; set; }

    public virtual Employee ApprovedFirstByNavigation { get; set; }

    public virtual Employee CreatedByNavigation { get; set; }

    public virtual InsuranceRate HealthInsurance { get; set; }

    public virtual ICollection<OvertimeRequest> OvertimeRequests { get; set; } = new List<OvertimeRequest>();

    public virtual ICollection<PayRunItem> PayRunItems { get; set; } = new List<PayRunItem>();

    public virtual Employee RejectedByNavigation { get; set; }

    public virtual SalaryPolicy SalaryPolicy { get; set; }

    public virtual InsuranceRate SocialInsurance { get; set; }

    public virtual Tax Tax { get; set; }

    public virtual InsuranceRate UnemployeeInsurance { get; set; }
}