// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class PayRunItem
{
    public int PayRunItemId { get; set; }

    public int PayRunId { get; set; }

    public int EmpId { get; set; }

    public decimal GrossPay { get; set; }

    public decimal Deductions { get; set; }

    public decimal NetPay { get; set; }

    public string Notes { get; set; }

    public virtual Employee Emp { get; set; }

    public virtual PayRun PayRun { get; set; }

    public virtual ICollection<PayRunComponent> PayRunComponents { get; set; } = new List<PayRunComponent>();
}