// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class SalaryPolicy
{
    public int SalId { get; set; }

    public string SalaryPolicyName { get; set; }

    public decimal WorkUnitValue { get; set; }

    public int YearlyPto { get; set; }

    public decimal OverclockMultiplier { get; set; }

    public DateTime EffectiveFrom { get; set; }

    public bool IsActive { get; set; }
}