// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class Tax
{
    public int TaxId { get; set; }

    public string TaxName { get; set; }

    public DateOnly EffectiveFrom { get; set; }

    public DateOnly? EffectiveTo { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<PayRun> PayRuns { get; set; } = new List<PayRun>();

    public virtual ICollection<TaxBracket> TaxBrackets { get; set; } = new List<TaxBracket>();
}