// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class TaxBracket
{
    public int BracketId { get; set; }

    public decimal LowerBound { get; set; }

    public decimal? UpperBound { get; set; }

    public decimal Rate { get; set; }

    public DateOnly EffectiveFrom { get; set; }

    public DateOnly? EffectiveTo { get; set; }
}