// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class Clockin
{
    public int CloId { get; set; }

    public int EmpId { get; set; }

    public DateTime? Date { get; set; }

    public float? CloCard { get; set; }

    public float? CloShiftCard { get; set; }

    public string ClockString { get; set; }

    public virtual Employee Emp { get; set; }
}