// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class DailyShift
{
    public int ShiftId { get; set; }

    public string ShiftName { get; set; }

    public string ShiftString { get; set; }

    public string ShiftDescription { get; set; }

    public decimal? ShiftWorkhour { get; set; }

    public virtual ICollection<WeeklyShift> WeeklyShiftFriDailyShifts { get; set; } = new List<WeeklyShift>();

    public virtual ICollection<WeeklyShift> WeeklyShiftMonDailyShifts { get; set; } = new List<WeeklyShift>();

    public virtual ICollection<WeeklyShift> WeeklyShiftSatDailyShifts { get; set; } = new List<WeeklyShift>();

    public virtual ICollection<WeeklyShift> WeeklyShiftSunDailyShifts { get; set; } = new List<WeeklyShift>();

    public virtual ICollection<WeeklyShift> WeeklyShiftThuDailyShifts { get; set; } = new List<WeeklyShift>();

    public virtual ICollection<WeeklyShift> WeeklyShiftTueDailyShifts { get; set; } = new List<WeeklyShift>();

    public virtual ICollection<WeeklyShift> WeeklyShiftWedDailyShifts { get; set; } = new List<WeeklyShift>();
}