// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class DailyShift
{
    public int ShiftIndex { get; set; }

    public string ShiftName { get; set; }

    public string ShiftString { get; set; }

    public string ShiftDescription { get; set; }

    public int? ShiftWorkhour { get; set; }
}