// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class Department
{
    public int DepId { get; set; }

    public string DepName { get; set; }

    public virtual ICollection<DepartmentWeeklyShift> DepartmentWeeklyShifts { get; set; } = new List<DepartmentWeeklyShift>();

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}