// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class EmployeeBalance
{
    public int Id { get; set; }

    public int EmpId { get; set; }

    public string Pto { get; set; }

    public string Sick { get; set; }

    public string Vacation { get; set; }

    public string Overtime { get; set; }

    public DateTime? LastUpdated { get; set; }

    public virtual Employee Emp { get; set; }
}