// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class EmployeeSalaryPreview
{
    public int PreviewId { get; set; }

    public int EmpId { get; set; }

    public int PayrollRunId { get; set; }

    public decimal BaseSalary { get; set; }

    public decimal Overtime { get; set; }

    public decimal Allowance { get; set; }

    public decimal Bonus { get; set; }

    public decimal GrossSalary { get; set; }

    public decimal SocialInsurance { get; set; }

    public decimal HealthInsurance { get; set; }

    public decimal UnemploymentInsurance { get; set; }

    public decimal PersonalIncomeTax { get; set; }

    public decimal TotalDeductions { get; set; }

    public decimal NetSalary { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int InsuranceRateSetId { get; set; }

    public virtual Employee CreatedByNavigation { get; set; }

    public virtual Employee Emp { get; set; }

    public virtual InsuranceRateSet InsuranceRateSet { get; set; }

    public virtual PayrollRun PayrollRun { get; set; }
}