// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class EmployeeRole
{
    public int RoleId { get; set; }

    public int EmpId { get; set; }

    public int RoleId1 { get; set; }

    public virtual Employee Emp { get; set; }

    public virtual Role RoleId1Navigation { get; set; }
}