// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class EmployeeAllowance
{
    public int Id { get; set; }

    public int EmpId { get; set; }

    public int TypeId { get; set; }

    public decimal? CustomValue { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string Status { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Employee CreatedByNavigation { get; set; }

    public virtual Employee Emp { get; set; }

    public virtual AllowanceType Type { get; set; }
}