// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class EmployeeDependent
{
    public int DependentId { get; set; }

    public int EmployeeId { get; set; }

    public string FullName { get; set; }

    public string Relationship { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Gender { get; set; }

    public string NationalId { get; set; }

    public bool IsTaxDependent { get; set; }

    public DateOnly EffectiveStartDate { get; set; }

    public DateOnly? EffectiveEndDate { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string Proof { get; set; }

    public virtual Employee Employee { get; set; }
}