// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class Employee
{
    public int EmpId { get; set; }

    public string EmpName { get; set; }

    public DateOnly? EmpDob { get; set; }

    public string EmpPhoneNumber { get; set; }

    public int? DepId { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public int? ClockinId { get; set; }

    public virtual ICollection<Clockin> Clockins { get; set; } = new List<Clockin>();

    public virtual Department Dep { get; set; }

    public virtual ICollection<EmployeeAllowance> EmployeeAllowanceCreatedByNavigations { get; set; } = new List<EmployeeAllowance>();

    public virtual ICollection<EmployeeAllowance> EmployeeAllowanceEmps { get; set; } = new List<EmployeeAllowance>();

    public virtual ICollection<EmployeeDependent> EmployeeDependents { get; set; } = new List<EmployeeDependent>();

    public virtual ICollection<EmployeePermission> EmployeePermissions { get; set; } = new List<EmployeePermission>();

    public virtual ICollection<EmployeeRole> EmployeeRoles { get; set; } = new List<EmployeeRole>();

    public virtual ICollection<EmployeeSalaryPreview> EmployeeSalaryPreviewCreatedByNavigations { get; set; } = new List<EmployeeSalaryPreview>();

    public virtual ICollection<EmployeeSalaryPreview> EmployeeSalaryPreviewEmps { get; set; } = new List<EmployeeSalaryPreview>();

    public virtual ICollection<EmployeeSalarySlip> EmployeeSalarySlipApprovedByNavigations { get; set; } = new List<EmployeeSalarySlip>();

    public virtual ICollection<EmployeeSalarySlip> EmployeeSalarySlipCreatedByNavigations { get; set; } = new List<EmployeeSalarySlip>();

    public virtual ICollection<EmployeeSalarySlip> EmployeeSalarySlipEmps { get; set; } = new List<EmployeeSalarySlip>();

    public virtual ICollection<Kpi> KpiAssignedByNavigations { get; set; } = new List<Kpi>();

    public virtual ICollection<Kpi> KpiEmps { get; set; } = new List<Kpi>();

    public virtual ICollection<LeaveRequest> LeaveRequestApprovedByNavigations { get; set; } = new List<LeaveRequest>();

    public virtual ICollection<LeaveRequest> LeaveRequestEmps { get; set; } = new List<LeaveRequest>();

    public virtual ICollection<OvertimeRate> OvertimeRates { get; set; } = new List<OvertimeRate>();

    public virtual ICollection<OvertimeRequest> OvertimeRequestApprovedByNavigations { get; set; } = new List<OvertimeRequest>();

    public virtual ICollection<OvertimeRequest> OvertimeRequestEmps { get; set; } = new List<OvertimeRequest>();

    public virtual ICollection<PayrollRun> PayrollRunApprovedFinalByNavigations { get; set; } = new List<PayrollRun>();

    public virtual ICollection<PayrollRun> PayrollRunApprovedFirstByNavigations { get; set; } = new List<PayrollRun>();

    public virtual ICollection<PayrollRun> PayrollRunCreatedByNavigations { get; set; } = new List<PayrollRun>();

}