// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class InsuranceRateSet
{
    public int InsuranceRateSetId { get; set; }

    public decimal SocialEmployeeRate { get; set; }

    public decimal SocialEmployerRate { get; set; }

    public decimal HealthEmployeeRate { get; set; }

    public decimal HealthEmployerRate { get; set; }

    public decimal UiEmployeeRate { get; set; }

    public decimal UiEmployerRate { get; set; }

    public string UiCapRule { get; set; }

    public string SiHiCapRule { get; set; }

    public DateOnly EffectiveFrom { get; set; }

    public DateOnly? EffectiveTo { get; set; }
}