// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class Kpi
{
    public int KpiId { get; set; }

    public int EmpId { get; set; }

    public int PeriodYear { get; set; }

    public int PeriodMonth { get; set; }

    public int KpiRate { get; set; }

    public bool? Prorate { get; set; }

    public int? AssignedBy { get; set; }

    public DateTime? AssignedAt { get; set; }

    public virtual Employee AssignedByNavigation { get; set; }

    public virtual Employee Emp { get; set; }

    public virtual ICollection<Kpicomponent> Kpicomponents { get; set; } = new List<Kpicomponent>();
}