// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class Kpicomponent
{
    public int KpiCompId { get; set; }

    public int KpiId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int TargetValue { get; set; }

    public int? AchievedValue { get; set; }

    public int Weight { get; set; }

    public decimal? SelfScore { get; set; }

    public decimal? AssignedScore { get; set; }

    public string SelfComment { get; set; }

    public string AssignerComment { get; set; }

    public virtual Kpi Kpi { get; set; }
}