// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class OvertimeRate
{
    public string OvertimeType { get; set; }

    public decimal RateMultiplier { get; set; }

    public DateTime? EffectiveDate { get; set; }

    public int? CreatedBy { get; set; }

    public int Id { get; set; }

    public virtual Employee CreatedByNavigation { get; set; }

    public virtual ICollection<OvertimeRequest> OvertimeRequests { get; set; } = new List<OvertimeRequest>();
}