// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class PayrollRun
{
    public int PayrollRunId { get; set; }

    public string Name { get; set; }

    public int PeriodMonth { get; set; }

    public int PeriodYear { get; set; }

    public string Status { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? ApprovedBy { get; set; }

    public DateTime? ApprovedDate { get; set; }

    public virtual Employee ApprovedByNavigation { get; set; }

    public virtual Employee CreatedByNavigation { get; set; }

    public virtual ICollection<EmployeeSalaryPreview> EmployeeSalaryPreviews { get; set; } = new List<EmployeeSalaryPreview>();

    public virtual ICollection<OvertimeRequest> OvertimeRequests { get; set; } = new List<OvertimeRequest>();
}