// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class PayRunComponent
{
    public int PayRunComponentId { get; set; }

    public int PayRunItemId { get; set; }

    public string ComponentType { get; set; }

    public string ComponentCode { get; set; }

    public string Description { get; set; }

    public decimal Amount { get; set; }

    public bool? Taxable { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual PayRunItem PayRunItem { get; set; }
}