// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class SalaryPolicy
{
    public int SalId { get; set; }

    public string SalName { get; set; }

    public int SalCardValue { get; set; }

    public int? SalYearlyPto { get; set; }

    public float SalOverclockMultiplier { get; set; }
}