// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AttendanceManagementPayrollSystem.Models;

public partial class WeeklyShift
{
    public int ShiftId { get; set; }

    public string ShiftName { get; set; }

    public int? MonDailyShiftIndex { get; set; }

    public int? TueDailyShiftIndex { get; set; }

    public int? WebDailyShiftIndex { get; set; }

    public int? ThuDailyShiftIndex { get; set; }

    public int? FriDailyShiftIndex { get; set; }

    public int? SatDailyShiftIndex { get; set; }

    public int? SunDailyShiftIndex { get; set; }

    public string ShiftDescription { get; set; }

    public virtual ICollection<DepartmentWeeklyShift> DepartmentWeeklyShifts { get; set; } = new List<DepartmentWeeklyShift>();
}